INSERT INTO `miejsce_kategoria` (`Id`, `Nazwa`) VALUES ('1', 'Kolejowe');
INSERT INTO `miejsce_kategoria` (`Id`, `Nazwa`) VALUES ('2', 'Hotele i pensjonaty');
INSERT INTO `miejsce_kategoria` (`Id`, `Nazwa`) VALUES ('3', 'Domy');
INSERT INTO `miejsce_kategoria` (`Id`, `Nazwa`) VALUES ('4', 'Industrialne');
INSERT INTO `miejsce_kategoria` (`Id`, `Nazwa`) VALUES ('5', 'Restauracje i kluby');
INSERT INTO `miejsce_kategoria` (`Id`, `Nazwa`) VALUES ('6', 'Rolnicze');
INSERT INTO `miejsce_kategoria` (`Id`, `Nazwa`) VALUES ('7', 'Zamki i pa³ace');
INSERT INTO `miejsce_kategoria` (`Id`, `Nazwa`) VALUES ('8', 'Podziemia');
INSERT INTO `miejsce_kategoria` (`Id`, `Nazwa`) VALUES ('9', 'Biurowce');
INSERT INTO `miejsce_kategoria` (`Id`, `Nazwa`) VALUES ('10', 'Militarne');
INSERT INTO `miejsce_kategoria` (`Id`, `Nazwa`) VALUES ('11', 'Szpitale');
INSERT INTO `miejsce_kategoria` (`Id`, `Nazwa`) VALUES ('12', 'Podziemia i tunele');
INSERT INTO `miejsce_kategoria` (`Id`, `Nazwa`) VALUES ('13', 'Inne');
